FROM ubuntu:24.04 AS executor64

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y gcc g++ cmake \
        libboost-all-dev bison \
        qt6-base-dev \
        libsdl1.2-dev libsdl2-dev \
        ninja-build ruby \
        waylandpp-dev

WORKDIR /files
